version: '3'
services:

 fullnode:
  image: bitshares/bitshares-core:latest
  ports:
   - "0.0.0.0:8090:8090"
  volumes:
  - "bitshares-fullnode:/var/lib/bitshares"
  - "bitshares-bins:/usr/local/bin"

 delayed_node:
  image: bitshares/bitshares-core:latest
  environment:
   - 'BITSHARESD_PLUGINS=delayed_node witness'
   - 'BITSHARESD_TRUSTED_NODE=ws://fullnode:8090'
  ports:
   - "0.0.0.0:8091:8090"
  volumes:
  - "bitshares-delayed_node:/var/lib/bitshares"
  links: 
  - fullnode

volumes:
 bitshares-fullnode:
 bitshares-delayed_node:
 bitshares-bins:
